name: Jest Tests

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: alchemy
          POSTGRES_PASSWORD: alchemy
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test
        env:
          CI: true
          DATABASE_URL: postgres://alchemy:alchemy@postgres:5432/alchemy
          COOKIE_NAME: session
          JWT_SECRET: ${process.env.JWT_SECRET}
          CLIENT_ID: ${process.env.CLIENT_ID}
          CLIENT_SECRET: ${process.env.CLIENT_SECRET}
          REDIRECT_URI: http://localhost:7890/api/v1/github/login/callback
